title:            Go database/sql tutorial
description:      Use database/sql effectively!
disqus_shortname: 
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://go-database-sql.org/

# Owner/author information
owner:
  name:           VividCortex
  avatar:         avatar.jpg
  bio:            
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        @VividCortex
  facebook:       
  github:         VividCortex
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   

# Background image to be tiled on all pages
background: ps_neutral.png

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Theme Setup
    url: /theme-setup
  - title: External Link
    url: http://mademistakes.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    UTC
future:      true
pygments:    true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 5

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
